# Generated by Django 6.0 on 2025-12-18 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("templates", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Invitation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("title", models.CharField(max_length=200, verbose_name="청첩장 제목")),
                ("url_slug", models.SlugField(max_length=100, unique=True, verbose_name="URL 슬러그")),
                (
                    "status",
                    models.CharField(
                        choices=[("DRAFT", "초안"), ("PUBLISHED", "발행됨"), ("ARCHIVED", "보관됨")],
                        default="DRAFT",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("groom_name", models.CharField(max_length=50, verbose_name="신랑 이름")),
                ("groom_father_name", models.CharField(blank=True, max_length=50, verbose_name="신랑 아버지")),
                ("groom_mother_name", models.CharField(blank=True, max_length=50, verbose_name="신랑 어머니")),
                ("groom_phone", models.CharField(blank=True, max_length=20, verbose_name="신랑 연락처")),
                ("bride_name", models.CharField(max_length=50, verbose_name="신부 이름")),
                ("bride_father_name", models.CharField(blank=True, max_length=50, verbose_name="신부 아버지")),
                ("bride_mother_name", models.CharField(blank=True, max_length=50, verbose_name="신부 어머니")),
                ("bride_phone", models.CharField(blank=True, max_length=20, verbose_name="신부 연락처")),
                ("wedding_date", models.DateTimeField(verbose_name="예식 일시")),
                ("wedding_location_name", models.CharField(blank=True, max_length=200, verbose_name="예식장 이름")),
                ("wedding_location_address", models.CharField(blank=True, max_length=300, verbose_name="예식장 주소")),
                (
                    "wedding_location_lat",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True, verbose_name="위도"),
                ),
                (
                    "wedding_location_lng",
                    models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True, verbose_name="경도"),
                ),
                ("invitation_message", models.TextField(blank=True, verbose_name="본문 메시지")),
                ("greeting_message", models.TextField(blank=True, verbose_name="인사말")),
                ("ending_message", models.TextField(blank=True, verbose_name="엔딩 문구")),
                ("background_animation", models.CharField(blank=True, max_length=50, verbose_name="배경 애니메이션")),
                ("background_color", models.CharField(default="#FFFFFF", max_length=20, verbose_name="배경 색")),
                ("font_family", models.CharField(default="default", max_length=50, verbose_name="폰트")),
                ("music_url", models.URLField(blank=True, max_length=500, verbose_name="배경음악 URL")),
                ("enable_rsvp", models.BooleanField(default=True, verbose_name="RSVP 기능 사용")),
                ("enable_guestbook", models.BooleanField(default=True, verbose_name="방명록 기능 사용")),
                ("enable_account_transfer", models.BooleanField(default=False, verbose_name="계좌정보 노출")),
                ("is_public", models.BooleanField(default=True, verbose_name="공개 여부")),
                ("view_count", models.IntegerField(default=0, verbose_name="조회수")),
                ("is_paid", models.BooleanField(default=False, verbose_name="결제 여부")),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("FREE", "무료"), ("PREMIUM", "프리미엄"), ("PREMIUM_PLUS", "프리미엄 플러스")],
                        default="FREE",
                        max_length=20,
                        verbose_name="플랜 타입",
                    ),
                ),
                ("published_at", models.DateTimeField(blank=True, null=True, verbose_name="발행 일시")),
                (
                    "template",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="invitations",
                        to="templates.template",
                        verbose_name="템플릿",
                    ),
                ),
            ],
            options={
                "verbose_name": "청첩장",
                "verbose_name_plural": "청첩장",
                "db_table": "invitations_invitation",
                "ordering": ["-created_at"],
            },
        ),
    ]
