# Generated by Django 6.0 on 2025-12-18 15:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invitations", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to=settings.AUTH_USER_MODEL,
                verbose_name="소유자",
            ),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["url_slug"], name="invitations_url_slu_148646_idx"),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["status"], name="invitations_status_47519c_idx"),
        ),
        migrations.AddIndex(
            model_name="invitation",
            index=models.Index(fields=["user", "status"], name="invitations_user_id_768526_idx"),
        ),
    ]
