# Generated by Django 6.0 on 2025-12-19 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Guestbook",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("author_name", models.CharField(max_length=100, verbose_name="작성자 이름")),
                ("message", models.TextField(verbose_name="방명록 내용")),
                ("is_public", models.BooleanField(default=True, verbose_name="공개 여부")),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="연락처")),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="guestbooks",
                        to="invitations.invitation",
                        verbose_name="청첩장",
                    ),
                ),
            ],
            options={
                "verbose_name": "방명록",
                "verbose_name_plural": "방명록",
                "db_table": "invitations_guestbook",
                "ordering": ["-created_at"],
                "indexes": [models.Index(fields=["invitation", "is_public"], name="invitations_invitat_130c77_idx")],
            },
        ),
        migrations.CreateModel(
            name="RSVP",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("guest_name", models.CharField(max_length=100, verbose_name="참석자 이름")),
                ("guest_count", models.IntegerField(default=1, verbose_name="참석 인원수")),
                (
                    "attendance_status",
                    models.CharField(
                        choices=[("ATTENDING", "참석"), ("NOT_ATTENDING", "불참석"), ("PENDING", "미정")],
                        default="PENDING",
                        max_length=20,
                        verbose_name="참석 여부",
                    ),
                ),
                ("phone", models.CharField(blank=True, max_length=20, verbose_name="연락처")),
                ("message", models.TextField(blank=True, verbose_name="메시지")),
                ("dietary_restrictions", models.TextField(blank=True, verbose_name="식이 제한사항")),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvps",
                        to="invitations.invitation",
                        verbose_name="청첩장",
                    ),
                ),
            ],
            options={
                "verbose_name": "RSVP",
                "verbose_name_plural": "RSVPs",
                "db_table": "invitations_rsvp",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(fields=["invitation", "attendance_status"], name="invitations_invitat_1c6bb5_idx")
                ],
            },
        ),
    ]
