# Generated by Django 6.0 on 2026-02-01 10:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("invitations", "0003_guestbook_rsvp"),
    ]

    operations = [
        migrations.AddField(
            model_name="invitation",
            name="background_effect",
            field=models.CharField(blank=True, max_length=50, verbose_name="배경 효과"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="background_texture",
            field=models.CharField(blank=True, max_length=50, verbose_name="배경 질감"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="font_color",
            field=models.CharField(default="#000000", max_length=20, verbose_name="글꼴 색상"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="font_weight",
            field=models.CharField(
                choices=[("NORMAL", "보통"), ("BOLD", "굵게"), ("LIGHT", "얇게")],
                default="NORMAL",
                max_length=20,
                verbose_name="글꼴 두께",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="greeting_name_display_type",
            field=models.CharField(
                choices=[("AUTO", "신랑·신부 이름 표시"), ("MANUAL", "성함 직접 입력")],
                default="AUTO",
                max_length=20,
                verbose_name="성함 표기 방식",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="greeting_name_manual",
            field=models.TextField(blank=True, verbose_name="직접 입력한 성함"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="greeting_subtitle",
            field=models.CharField(blank=True, max_length=200, verbose_name="인사말 소제목"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="greeting_title",
            field=models.CharField(blank=True, max_length=200, verbose_name="인사말 제목"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="lock_map",
            field=models.BooleanField(default=False, verbose_name="지도 잠금"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="photo_effect",
            field=models.CharField(
                blank=True,
                choices=[("NONE", "없음"), ("FOG", "안개"), ("WAVE", "물결"), ("OTHER", "기타")],
                default="NONE",
                max_length=20,
                verbose_name="사진 효과",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="photo_frame_type",
            field=models.CharField(
                choices=[("BASIC", "기본"), ("FILL", "채우기"), ("OVAL", "타원"), ("ARCH", "아치"), ("FRAME", "액자")],
                default="BASIC",
                max_length=20,
                verbose_name="사진 프레임 타입",
            ),
        ),
        migrations.AddField(
            model_name="invitation",
            name="photo_urls",
            field=models.JSONField(blank=True, default=list, verbose_name="사진 URL 목록"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="prevent_zoom",
            field=models.BooleanField(default=True, verbose_name="청첩장 확대 방지"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="scroll_animation",
            field=models.BooleanField(default=False, verbose_name="스크롤 시 등장 이벤트"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="show_calendar",
            field=models.BooleanField(default=True, verbose_name="캘린더 표시"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="show_countdown",
            field=models.BooleanField(default=False, verbose_name="카운트다운 표시"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="show_dday",
            field=models.BooleanField(default=False, verbose_name="D-DAY 표시"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="show_map",
            field=models.BooleanField(default=True, verbose_name="지도 표시"),
        ),
        migrations.AddField(
            model_name="invitation",
            name="show_navigation",
            field=models.BooleanField(default=False, verbose_name="네비게이션 버튼 표시"),
        ),
        migrations.AlterField(
            model_name="invitation",
            name="greeting_message",
            field=models.TextField(blank=True, verbose_name="인사말 내용"),
        ),
        migrations.CreateModel(
            name="Transportation",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                (
                    "transport_type",
                    models.CharField(
                        choices=[("BUS", "버스"), ("SUBWAY", "지하철"), ("CAR", "자가용"), ("WALK", "도보")],
                        max_length=20,
                        verbose_name="교통수단 종류",
                    ),
                ),
                ("content", models.TextField(blank=True, verbose_name="내용")),
                ("order", models.IntegerField(default=0, verbose_name="순서")),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="transportations",
                        to="invitations.invitation",
                        verbose_name="청첩장",
                    ),
                ),
            ],
            options={
                "verbose_name": "교통수단",
                "verbose_name_plural": "교통수단",
                "db_table": "invitations_transportation",
                "ordering": ["order", "created_at"],
                "indexes": [models.Index(fields=["invitation", "order"], name="invitations_invitat_7ec5b6_idx")],
            },
        ),
    ]
