# Generated by Django 6.0 on 2025-12-18 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Template",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("name", models.CharField(max_length=100, verbose_name="템플릿 이름")),
                ("description", models.TextField(blank=True, verbose_name="설명")),
                ("thumbnail_url", models.URLField(max_length=500, verbose_name="썸네일 URL")),
                ("preview_url", models.URLField(blank=True, max_length=500, verbose_name="프리뷰 URL")),
                (
                    "category",
                    models.CharField(
                        choices=[
                            ("MODERN", "모던"),
                            ("CLASSIC", "클래식"),
                            ("FLORAL", "플로럴"),
                            ("MINIMAL", "미니멀"),
                            ("ROMANTIC", "로맨틱"),
                        ],
                        max_length=50,
                        verbose_name="카테고리",
                    ),
                ),
                ("is_premium", models.BooleanField(default=False, verbose_name="프리미엄 여부")),
                ("is_active", models.BooleanField(default=True, verbose_name="사용 가능 여부")),
                ("usage_count", models.IntegerField(default=0, verbose_name="사용 횟수")),
            ],
            options={
                "verbose_name": "템플릿",
                "verbose_name_plural": "템플릿",
                "db_table": "templates_template",
                "ordering": ["-created_at"],
            },
        ),
    ]
