# Generated by Django 6.0 on 2026-02-01 10:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("templates", "0002_template_sample_slug"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserTemplate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("name", models.CharField(max_length=100, verbose_name="템플릿 이름")),
                ("template_data", models.JSONField(default=dict, verbose_name="템플릿 데이터")),
                ("is_default", models.BooleanField(default=False, verbose_name="기본 템플릿 여부")),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="user_templates",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="소유자",
                    ),
                ),
            ],
            options={
                "verbose_name": "사용자 템플릿",
                "verbose_name_plural": "사용자 템플릿",
                "db_table": "templates_user_template",
                "ordering": ["-is_default", "-created_at"],
                "indexes": [models.Index(fields=["user", "is_default"], name="templates_u_user_id_ccef38_idx")],
            },
        ),
    ]
