# Generated by Django 6.0 on 2025-12-18 15:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("invitations", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Payment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("created_at", models.DateTimeField(auto_now_add=True, verbose_name="생성일시")),
                ("updated_at", models.DateTimeField(auto_now=True, verbose_name="수정일시")),
                ("order_id", models.CharField(max_length=100, unique=True, verbose_name="주문 ID")),
                ("payment_key", models.CharField(max_length=200, verbose_name="결제 키")),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10, verbose_name="금액")),
                (
                    "plan_type",
                    models.CharField(
                        choices=[("FREE", "무료"), ("PREMIUM", "프리미엄"), ("PREMIUM_PLUS", "프리미엄 플러스")],
                        max_length=20,
                        verbose_name="플랜 타입",
                    ),
                ),
                ("payment_method", models.CharField(max_length=50, verbose_name="결제 수단")),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "대기중"),
                            ("COMPLETED", "완료"),
                            ("FAILED", "실패"),
                            ("REFUNDED", "환불됨"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="상태",
                    ),
                ),
                ("paid_at", models.DateTimeField(blank=True, null=True, verbose_name="결제 일시")),
                ("refunded_at", models.DateTimeField(blank=True, null=True, verbose_name="환불 일시")),
                ("refund_reason", models.TextField(blank=True, verbose_name="환불 사유")),
                (
                    "invitation",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="invitations.invitation",
                        verbose_name="청첩장",
                    ),
                ),
            ],
            options={
                "verbose_name": "결제",
                "verbose_name_plural": "결제",
                "db_table": "payments_payment",
                "ordering": ["-created_at"],
            },
        ),
    ]
